CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(100),
    login varchar(50) not null,
    name varchar(100),
    birthdate date
);

CREATE TABLE IF NOT EXISTS friendship (
    user_id BIGINT not null,
    friend_id BIGINT not null,
    status boolean not null,
    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) not null,
    description varchar(200),
    release_date date,
    duration int
);

CREATE TABLE IF NOT EXISTS films_likes (
    film_id BIGINT,
    user_id BIGINT,
    PRIMARY KEY (film_id, user_id)
);

CREATE TYPE IF NOT EXISTS rating_mpa_type AS ENUM ('g', 'pg', 'pg13', 'r', 'nc17');

CREATE TABLE IF NOT EXISTS rating (
    id int not null,
    name rating_mpa_type,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS films_ratings (
    film_id BIGINT,
    rating_id int,
    PRIMARY KEY (film_id, rating_id)
);

CREATE TABLE IF NOT EXISTS genres (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100)
);

CREATE TABLE IF NOT EXISTS films_genres (
    film_id BIGINT,
    genre_id int,
    PRIMARY KEY (film_id, genre_id)
);
