CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(100),
    login varchar(50) not null,
    name varchar(100),
    birthday date
);

CREATE TYPE IF NOT EXISTS rating_mpa_type AS ENUM ('g', 'pg', 'pg13', 'r', 'nc17');

CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) not null,
    description varchar(200),
    release_date date,
    duration int,
    rating_mpa rating_mpa_type
);

CREATE TABLE IF NOT EXISTS genres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100)
);

CREATE TABLE IF NOT EXISTS films_likes (
    film_id int,
    user_id int,
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS friendship (
    requestor_id int not null,
    approver_id int not null,
    status boolean not null,
    request_dttm timestamp default current_timestamp,
    approve_dttm timestamp,
    PRIMARY KEY (requestor_id, approver_id)
);

CREATE TABLE IF NOT EXISTS films_genres (
    film_id int,
    genre_id int,
    PRIMARY KEY (film_id, genre_id)
);
